### ISSUE TITLE
Can't read input from argv

### ISSUE THREAD

**Issue by MacTynow** [drone/drone-python#10]
Hi,

I wrote https://github.com/mactynow/drone-s3cache and it's working fine when I pass values from stdin. However when I try to add it to my pipeline I get the following error :
```
Traceback (most recent call last):
  File "/opt/drone/plugin/main.py", line 39, in <module>
    main()
  File "/opt/drone/plugin/main.py", line 13, in main
    payload = drone.plugin.get_input()
  File "/usr/lib/python2.7/site-packages/drone/plugin/input.py", line 23, in get_input
    payload_str = _get_input_from_stdin()
  File "/usr/lib/python2.7/site-packages/drone/plugin/input.py", line 38, in _get_input_from_stdin
    raise ValueError("No plugin input was found in argv or stdin.")
ValueError: No plugin input was found in argv or stdin.
```

I checked in https://github.com/drone/drone-python/blob/master/drone/plugin/input.py and it should work, except if drone doesn't pass its arguments after `--` anymore... Any ideas? 

If there is something that needs to be fixed I'll be happy to issue a PR.

**Comment by MacTynow** [comment]
From what I see, it's now passing everything as environment variables. Let me know if I'm wrong.

**Comment by gtaylor** [comment]
This is correct if you are running a version of Drone later than 0.4 (for which this library was made for). You probably don't need drone-python at all these days, since we're no longer parsing stdin/argv.

**Comment by MacTynow** [comment]
Alright, I'm running 0.5, that's why. Well, at least it generates the docs etc... so that's actually quite useful. I'm closing this, thanks!

**Comment by so0k** [comment]
@MacTynow 
> it generates the docs

you still need to write docs! 😛
