### ISSUE TITLE
Set up ReadTheDocs webhook

### ISSUE THREAD

**Issue by gtaylor** [drone/drone-python#2]
The Python ecosystem makes heavy use of [ReadTheDocs](https://readthedocs.org/). Docs are built and hosted on RTD. The trigger ends up being a GitHub webhook.

I've already got everything working on the RTD side, I just need a webhook on this repo added against the following URL: https://readthedocs.org/build/drone-python

Here is what the current docs look like so far: http://drone-python.readthedocs.org/

**Comment by bradrydzewski** [comment]
docs looking great, I've added you as an admin so that you can configure webhooks, or any other repository configurations, as needed

**Comment by gtaylor** [comment]
Wonderful, thanks!
