### ISSUE TITLE
Basic HTTP client

### ISSUE THREAD

**Issue by mbeacom** [drone/drone-python#9]
Add basic HTTP authentication and basic functionality mirroring the [drone/drone-go](https://github.com/drone/drone-go) client functionality.

**NOTE:** I can probably tackle this sometime throughout this week, pending merging of the python 2.7 changes.

**Comment by mbeacom** [comment]
Awaiting the green light from @bradrydzewski to start modifying the `drone/swagger` schema.

**Comment by mbeacom** [comment]
I'll try to get the swagger stubs in sometime before the end of the week!

**Comment by zaghaghi** [comment]
Hi,

I can't find Drone API client in this repository and other drone repositories, so here is my attempt in doing this, [drone-python](https://github.com/zaghaghi/drone-python).

**Comment by mbeacom** [comment]
@zaghaghi Yeah, apologies.  This repository has been (for all intents and purposes) unmaintained for a few years.  I was attempting to get some internal buy-in to move forward with generating the API via the drone swagger schema, but didn't make a whole lot of headway while communicating with some drone contributors. 😄 I'd say go for maintaining your own client until they say otherwise... I'd look into generating off of the official swagger spec, though.
